In [1]:
import pandas as pd

from pathlib import Path

In [2]:
import utils

import importlib
importlib.reload(utils)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.

In [3]:
base = Path.home() / "kitti"
train_dir = base / "training"
train_labels_dir = train_dir / "label_2"
kitti_train_labels = sorted(train_labels_dir.glob("*.txt"))

In [4]:
object_types = []
extents = []
for label_file in kitti_train_labels:
    labels = utils.parse_label_file(label_file)
    for label in labels:
        object_types.append(label["type"])
        extents.append(label["dimensions"])

In [6]:
df = pd.DataFrame({
    'type': object_types,
    'height': [extent[0] for extent in extents],
    'width': [extent[1] for extent in extents],
    'length': [extent[2] for extent in extents],
})
stats = df.groupby('type').agg(['mean', 'std'])
stats

                  height               width               length
                    mean       std      mean       std       mean       std
type
Car             1.526083  0.136697  1.628590  0.102164   3.883954  0.425924
Cyclist         1.737203  0.094825  0.596773  0.124212   1.763546  0.176663
DontCare       -1.000000  0.000000 -1.000000  0.000000  -1.000000  0.000000
Misc            1.907133  0.814640  1.513834  0.673935   3.575591  2.859822
Pedestrian      1.760706  0.113263  0.660189  0.142667   0.842284  0.234926
Person_sitting  1.274955  0.110211  0.594910  0.079545   0.802027  0.222930
Tram            3.528924  0.175785  2.543738  0.215425  16.094266  7.859962
Truck           3.251709  0.449054  2.585091  0.216564  10.109077  2.859795
Van             2.206592  0.325038  1.902080  0.172881   5.078367  0.831094

In [8]:
stats.loc[['Car', 'Pedestrian', 'Cyclist']]

              height               width              length
                mean       std      mean       std      mean       std
type
Car         1.526083  0.136697  1.628590  0.102164  3.883954  0.425924
Pedestrian  1.760706  0.113263  0.660189  0.142667  0.842284  0.234926
Cyclist     1.737203  0.094825  0.596773  0.124212  1.763546  0.176663